# Generated by Django 5.1.4 on 2025-01-11 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name="Image de l'article")),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du site')),
                ('sous_titre', models.CharField(max_length=100, verbose_name='Titre du site')),
                ('description', models.CharField(max_length=100, verbose_name='Description du site')),
                ('nombre_vues', models.IntegerField(null=True, verbose_name='Description du site')),
                ('date_publication', models.DateField(verbose_name="Date du publication de l'article")),
                ('categorie', models.CharField(max_length=100, verbose_name="Catégorie de l'article")),
                ('nbr_jaime_x', models.IntegerField(null=True, verbose_name="Notre de j'aime pour cette article")),
                ('nbr_jaime_y', models.IntegerField(null=True, verbose_name="Nombre de ce qui n'ont pas aimé")),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description_courte', models.CharField(max_length=100, verbose_name='Description Courte')),
                ('description', models.CharField(max_length=100, verbose_name='Description logn')),
                ('date_creer', models.DateField(verbose_name='Date')),
                ('fichier', models.BinaryField()),
                ('type_fichier', models.CharField(choices=[('0', 'Image'), ('1', 'Document'), ('2', 'Video'), ('3', 'Audio')], max_length=100, verbose_name='Type du fichier')),
                ('nbr_jaime_x', models.IntegerField(null=True, verbose_name="Notre de j'aime pour cette article")),
                ('nbr_jaime_y', models.IntegerField(null=True, verbose_name="Nombre de ce qui n'ont pas aimé")),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Icone fontawson au format htmp exemple : <i class='fas fa-users'></i>", max_length=100, verbose_name='Icone')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libelle Produit')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du Produit')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('lien_site_web', models.CharField(max_length=100, verbose_name='Description')),
                ('date_ajouter', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Icone fontawson au format htmp exemple : <i class='fas fa-users'></i>", max_length=100, verbose_name='Icone')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libelle Service')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du Service')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('date_ajouter', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du site')),
                ('sloga', models.CharField(max_length=100, verbose_name='Sloga du site')),
                ('description', models.CharField(max_length=100, verbose_name='Description du site')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Montant lettre')),
                ('type_clien', models.CharField(choices=[('0', 'Particulier'), ('1', 'Société'), ('2', 'Organisation')], max_length=100, verbose_name='Type du fichier')),
                ('telephone', models.CharField(max_length=100, verbose_name='Numéro de téléphone')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse physique du client')),
                ('description', models.CharField(max_length=100, verbose_name='Description du client')),
                ('reference', models.CharField(max_length=100, verbose_name='Description du client')),
                ('lien_site_web', models.CharField(max_length=100, null=True, verbose_name='Lien site internet')),
                ('date_inscrit', models.DateField()),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence du projet')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé du projet')),
                ('Budget', models.IntegerField()),
                ('date_du_debut', models.DateField()),
                ('date_du_fin', models.DateField()),
                ('description', models.CharField(max_length=100, verbose_name='Description du projet')),
                ('email_a_contacter', models.CharField(max_length=100, verbose_name='Adresse mail du responsable à contacter pour cette projet')),
                ('telephone', models.CharField(max_length=100, verbose_name='Adresse mail du responsable à contacter pour cette projet')),
                ('evolution_du_projet', models.IntegerField(null=True, verbose_name='Evolution du projet en pourçentange')),
                ('date_ajouter', models.DateField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_vitrine.clients', verbose_name='Utilisateur')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_vitrine.services', verbose_name='Service')),
            ],
        ),
    ]
