# Generated by Django 5.1.4 on 2025-01-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('date_inscrit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration_utilissssateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('fonction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_vitrine.fonctions', verbose_name='Fonction')),
            ],
        ),
    ]
