# Generated by Django 5.1.4 on 2025-01-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vitrine', '0003_configuration_utilissssateur_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_utilissssateur',
            name='photo_profil',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo profil'),
        ),
    ]
