# Generated by Django 5.1.4 on 2025-01-31 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vitrine', '0005_configuration_utilissssateur_is_equipe_educ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='nombre_vues',
            field=models.IntegerField(null=True, verbose_name='Nombre vue'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sous_titre',
            field=models.CharField(max_length=100, verbose_name='Sous Titre du site'),
        ),
    ]
