# Generated by Django 5.1.4 on 2025-01-31 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vitrine', '0006_blog_utilisateur_alter_blog_nombre_vues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='nom_clien',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom client'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Logo société ou particulier'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='reference',
            field=models.CharField(max_length=100, verbose_name='Référence du client'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_clien',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Société', 'Société'), ('Organisation', 'Organisation')], max_length=100, verbose_name='Type du fichier'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_vitrine.clients', verbose_name='Cliet'),
        ),
    ]
