# Generated by Django 5.1.4 on 2025-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vitrine', '0007_clients_nom_clien_alter_clients_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image ou logo du projet'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='Budget',
            field=models.IntegerField(help_text='En dollar ($)'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='telephone',
            field=models.CharField(max_length=100, verbose_name='Téléphone'),
        ),
    ]
