# Generated by Django 5.1.4 on 2025-02-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vitrine', '0008_projets_image_alter_projets_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=100, verbose_name="Description de l'article"),
        ),
    ]
