# Generated by Django 5.1.4 on 2025-02-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vitrine', '0009_alter_blog_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=10000, verbose_name="Description de l'article"),
        ),
        migrations.CreateModel(
            name='Commentaire_blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du commentaire')),
                ('text', models.TextField(max_length=10000, verbose_name='commentaire')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_vitrine.blog', verbose_name='Article')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Article')),
            ],
        ),
    ]
